@baseUrl = http://localhost:3333

POST {{baseUrl}}/users
Content-Type: application/json

{
    "name": "Test User",
    "email": "testemail@example.com",
    "password": "#Test123"
}

###
POST {{baseUrl}}/users/auth
Content-Type: application/json

{
    "email": "testemail@example.com",
    "password": "#Test123"
}