name: Run Unit Tests

on:
  push:
    branches:
      - main
jobs:
  run-unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Use a recent version of checkout

      - name: Set up Node.js
        uses: actions/setup-node@v4 # Use a recent version of setup-node
        with:
          node-version: '20.x' # Use a recent LTS version
          cache: 'npm' # Cache npm dependencies

      - name: Install dependencies
        run: npm ci # Use clean install for reliability

      - name: Run unit tests
        run: npm test # Runs the "test": "vitest run" script from package.json
